### ISSUE TITLE
[Refactor] 채팅 - 멤버 연결

### ISSUE THREAD

**Issue by usingjun** [prgrms-web-devcourse-final-project/WEB1_2_BUMBLEBEE_BE#110]
## ⛏️ 리팩토링 할 기능
> 채팅 - 멤버 연결

<br>

## 🪜 변경 전 상황과 변경 이유
> 변경 전의 상황과 변경하려는 이유를 작성해주세요.  
단순 채팅 구현 -> 멤버, 사업자 연결 +  테스트

<br>

## ✨ 변경 후 예상
> 변경후의 예상하는 구조를 작성해주세요.  

<br>

## 📝 작업 상세 내용

- [ ] 멤버 연결
- [ ] 사업자 연결
- [ ] 성능 테스트

<br>

**Comment by jjyutm4532** [comment]
Hello, we tried to solve the issue.

This is what we did:

This change connects the chat functionality with members and businesses, and prepares for performance testing. It modifies the ChatMessage, ChatService, and ChatController classes to include member and business information.

You can review changes in this commit: https://github.com/jjyutm4532/prgrms-web-devcourse-final-project-WEB1_2_BUMBLEBEE_BE-110/commit/6b73c7dcda5874b4136d6c5f44dc7d6fe904f9c8.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.
