### ISSUE TITLE
[Refactor] 레디스 SortedSet 적용시 ttl 사용하지 못하는 문제

### ISSUE THREAD

**Issue by usingjun** [prgrms-web-devcourse-final-project/WEB1_2_BUMBLEBEE_BE#170]
## ⛏️ 리팩토링 할 기능
레디스 SortedSet 적용시 ttl 사용하지 못하는 문제

<br>

## 🪜 변경 전 상황과 변경 이유
채팅메시지를 레디스에서 조회 시 시간 순서대로 처리하지 못함.
-> 해결을 위해 레디스 Zscore을 활요한 SortedSet 사용

Issue : 레디스 SortedSet 적용시 ttl 사용하지 못하는 문제

<br>

## ✨ 변경 후 예상

<br>

## 📝 작업 상세 내용

- [ ] 내용 1
- [ ] 내용 2

<br>

@Account-4-Review

찾아보니 아래 3가지 방법이 있다고 하는데 2번 방법이 좋아보이는데 어떤 방법이 좋을까요?

- 방법 1: Redis의 만료 기능을 활용
Redis에서 TTL을 개별적으로 적용할 수 없으므로, TTL과 데이터 정렬을 모두 지원하려면 키를 개별적으로 생성해야 합니다. Sorted Set 사용 시에는 기본적으로 만료 기능을 직접 처리해야 합니다.

- 방법 2: 주기적으로 오래된 데이터를 삭제
flushMessagesToDatabase처럼 오래된 데이터를 삭제하는 별도 메서드를 작성하여 TTL을 구현할 수 있습니다.

`
public void removeExpiredMessages(Long roomId) {
    String redisKey = REDIS_MESSAGE_KEY_PREFIX + roomId;

    // 현재 시간 이전의 메시지 삭제
    double cutoffTime = LocalDateTime.now().minusSeconds(messageTtl).toEpochSecond(ZoneOffset.UTC);
    redisTemplate.opsForZSet().removeRangeByScore(redisKey, 0, cutoffTime);
}
`

removeRangeByScore를 사용해 Redis에서 만료된 메시지를 삭제합니다.
messageTtl 값을 활용해 TTL 기준을 계산합니다.
이 작업은 스케줄러나 주기적인 호출로 처리할 수 있습니다.

- 방법 3: MySQL에 저장하면서 Redis 데이터 삭제
Redis에 데이터가 오래 쌓이지 않도록, flushMessagesToDatabase 호출 시 Redis의 데이터를 모두 삭제하는 방식으로 관리합니다.

**Comment by Account-4-Review** [comment]
지금 상황이면 2번이 최선일 것 같긴 하네요.
다만, 어차피 채팅방은 전체로 캐싱을 하는 느낌이라서, 1번도 가능하지 않을까 싶어요.
일부 메시지만 캐싱하는 경우는 없으니까요.

**Comment by usingjun** [comment]
감사합니다:) 일단 2번으로 시도해보겠습니다!!
