### ISSUE TITLE
[Refactor] Business Controller Test코드 JWT 연동

### ISSUE THREAD

**Issue by Si-rauis** [prgrms-web-devcourse-final-project/WEB1_2_BUMBLEBEE_BE#85]
## ⛏️ 리팩토링 할 기능
> 리팩토링 할 기능에 대해 간단히 적어주세요.  

Business Controller Test코드 JWT 연동

<br>

## 🪜 변경 전 상황과 변경 이유
> 변경 전의 상황과 변경하려는 이유를 작성해주세요.  

권한이 필요한 도메인의 경우 토큰을 받고 요청하는 로직이 필수

<br>

## ✨ 변경 후 예상
> 변경후의 예상하는 구조를 작성해주세요.  

Business 회원가입 -> 로그인 시도 -> 토큰 반환 -> 수정, 조회, 삭제 요청

<br>

## 📝 작업 상세 내용

- [ ] Business Controller Test코드 JWT 연동

<br>

**Comment by lkilu6456546** [comment]
Hello, I tried to solve the issue.

This is what I did:

Updated BusinessControllerTest to include JWT authentication for protected endpoints. Added tests for login, and modified existing tests to use JWT token for authorization.

You can review changes in this commit: https://github.com/lkilu6456546/prgrms-web-devcourse-final-project-WEB1_2_BUMBLEBEE_BE-85/commit/b2b0db8988103824f8159c4b52720e990c440028.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.
